[2022-07-24 12:51:52,478] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.request_palamentar manual__2022-07-24T12:51:52.017885+00:00 [queued]>
[2022-07-24 12:51:52,486] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.request_palamentar manual__2022-07-24T12:51:52.017885+00:00 [queued]>
[2022-07-24 12:51:52,487] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-24 12:51:52,488] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-07-24 12:51:52,490] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-24 12:51:52,501] {taskinstance.py:1377} INFO - Executing <Task(SimpleHttpOperator): request_palamentar> on 2022-07-24 12:51:52.017885+00:00
[2022-07-24 12:51:52,505] {standard_task_runner.py:52} INFO - Started process 1177 to run task
[2022-07-24 12:51:52,508] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial_request', 'request_palamentar', 'manual__2022-07-24T12:51:52.017885+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmpvr48qvmg', '--error-file', '/tmp/tmpynmuj3p_']
[2022-07-24 12:51:52,509] {standard_task_runner.py:80} INFO - Job 8: Subtask request_palamentar
[2022-07-24 12:51:52,550] {task_command.py:370} INFO - Running <TaskInstance: tutorial_request.request_palamentar manual__2022-07-24T12:51:52.017885+00:00 [running]> on host 6e14261407f3
[2022-07-24 12:51:52,597] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial_request
AIRFLOW_CTX_TASK_ID=request_palamentar
AIRFLOW_CTX_EXECUTION_DATE=2022-07-24T12:51:52.017885+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-24T12:51:52.017885+00:00
[2022-07-24 12:51:52,599] {http.py:102} INFO - Calling HTTP method
[2022-07-24 12:51:52,606] {base.py:68} INFO - Using connection ID 'request_lakehouse' for task execution.
[2022-07-24 12:51:52,609] {http.py:129} INFO - Sending 'GET' to url: http://host.docker.internal:5000/extract/senators
[2022-07-24 12:51:53,520] {logging_mixin.py:115} INFO - RESPONSE <Response [200]>
[2022-07-24 12:51:53,526] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 109, in execute
    if not self.response_check(response, **kwargs):
  File "/opt/airflow/dags/hello.py", line 55, in <lambda>
    response_check=lambda response: handle_response(response),
  File "/opt/airflow/dags/hello.py", line 12, in handle_response
    if response.code == 200:
AttributeError: 'Response' object has no attribute 'code'
[2022-07-24 12:51:53,549] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial_request, task_id=request_palamentar, execution_date=20220724T125152, start_date=20220724T125152, end_date=20220724T125153
[2022-07-24 12:51:53,565] {standard_task_runner.py:97} ERROR - Failed to execute job 8 for task request_palamentar ('Response' object has no attribute 'code'; 1177)
[2022-07-24 12:51:53,623] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-24 12:51:53,667] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
