[2022-07-24 12:50:19,079] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.request_palamentar manual__2022-07-24T12:50:18.231422+00:00 [queued]>
[2022-07-24 12:50:19,087] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: tutorial_request.request_palamentar manual__2022-07-24T12:50:18.231422+00:00 [queued]>
[2022-07-24 12:50:19,088] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-07-24 12:50:19,089] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-07-24 12:50:19,091] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-07-24 12:50:19,103] {taskinstance.py:1377} INFO - Executing <Task(SimpleHttpOperator): request_palamentar> on 2022-07-24 12:50:18.231422+00:00
[2022-07-24 12:50:19,108] {standard_task_runner.py:52} INFO - Started process 1100 to run task
[2022-07-24 12:50:19,113] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'tutorial_request', 'request_palamentar', 'manual__2022-07-24T12:50:18.231422+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/hello.py', '--cfg-path', '/tmp/tmpbze6ovnk', '--error-file', '/tmp/tmpnqcl1r95']
[2022-07-24 12:50:19,115] {standard_task_runner.py:80} INFO - Job 5: Subtask request_palamentar
[2022-07-24 12:50:19,171] {task_command.py:370} INFO - Running <TaskInstance: tutorial_request.request_palamentar manual__2022-07-24T12:50:18.231422+00:00 [running]> on host 6e14261407f3
[2022-07-24 12:50:19,222] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=tutorial_request
AIRFLOW_CTX_TASK_ID=request_palamentar
AIRFLOW_CTX_EXECUTION_DATE=2022-07-24T12:50:18.231422+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-07-24T12:50:18.231422+00:00
[2022-07-24 12:50:19,223] {http.py:102} INFO - Calling HTTP method
[2022-07-24 12:50:19,234] {base.py:68} INFO - Using connection ID 'request_lakehouse' for task execution.
[2022-07-24 12:50:19,240] {http.py:129} INFO - Sending 'GET' to url: http://host.docker.internal:5000/extract/senators
[2022-07-24 12:50:21,437] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 109, in execute
    if not self.response_check(response, **kwargs):
  File "/opt/airflow/dags/hello.py", line 54, in <lambda>
    response_check=lambda response: handle_response(response),
  File "/opt/airflow/dags/hello.py", line 11, in handle_response
    if response.code == 200:
AttributeError: 'Response' object has no attribute 'code'
[2022-07-24 12:50:21,451] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=tutorial_request, task_id=request_palamentar, execution_date=20220724T125018, start_date=20220724T125019, end_date=20220724T125021
[2022-07-24 12:50:21,468] {standard_task_runner.py:97} ERROR - Failed to execute job 5 for task request_palamentar ('Response' object has no attribute 'code'; 1100)
[2022-07-24 12:50:21,480] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-07-24 12:50:21,506] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
